### ISSUE TITLE
Aspect ratio IOS

### ISSUE THREAD

**Issue by ricardocosta43** [flutter-cavalry/fc_native_image_resize#1]
In iOS version 17.2 the aspect ratio is not maintained

**Comment by mgenware** [comment]
Hi, iOS always keeps aspect ratio. Here's an example of resizing a big picture to 300x300 resulting in 300x201 in simulator:

<img width="505" alt="image" src="https://github.com/flutter-cavalry/fc_native_image_resize/assets/11565096/5cd45195-084b-4a37-9099-1040639d25d5">

Feel free to attach any code to repro the issue

**Comment by ricardocosta43** [comment]
Hello, sorry I didn't send examples.
Just so you understand, my case is as follows. I need to resize the photos because I'm not going to use image_picker.

See how the resize looks in your plugin (IOS only, Android works perfectly)

![teste 1](https://github.com/flutter-cavalry/fc_native_image_resize/assets/12566796/acdc5d0a-e853-4afe-84b3-20b400b3ce8b)

![teste2](https://github.com/flutter-cavalry/fc_native_image_resize/assets/12566796/e50c9ff4-fa29-4f28-974d-e06b685c303d)

In the image picker I do the same thing I do in your plugin and this distortion does not happen
see the codes below

![Captura de Tela 2024-01-31 às 02 19 35](https://github.com/flutter-cavalry/fc_native_image_resize/assets/12566796/efe9f73b-aa41-4902-bc44-527d80f046f7)

![Captura de Tela 2024-01-31 às 02 20 53](https://github.com/flutter-cavalry/fc_native_image_resize/assets/12566796/1bf06e60-64eb-4eee-8e6a-6aade09a88d1)

Maybe this will help you find the problem
Maybe you use the same calculation that image_picker does.
I don't know if it's possible to find this public code

**Comment by mgenware** [comment]
Thanks for the feedback. Fixed in v0.7.0!
