### ISSUE TITLE
The compressed image exceeds the original image size

### ISSUE THREAD

**Issue by Dec-QXY** [flutter-cavalry/fc_native_image_resize#2]
I encountered the following problem during the process of compressing images: the original image width is 1080, and I specified the compressed width as 2000, which will cause the image to increase. I think this is a bug.

**Comment by Dec-QXY** [comment]
And the compressed image will have a serious jagged feeling.

**Comment by mgenware** [comment]
@Dec-QXY which platform?

**Comment by Dec-QXY** [comment]
My device is android 10

**Comment by mgenware** [comment]
Try `v0.10.0` and make sure `keepAspectRatio` is true, it won't upscale images.
